### ISSUE TITLE
Uncontrolled looping when peer closes connection

### ISSUE THREAD

**Issue by fghibellini** [lucasdicioccio/http2-client#64]
https://github.com/lucasdicioccio/http2-client/blob/3c7996b8161154be41e354687423eec107322d43/src/Network/HTTP2/Client/RawConnection.hs#L126 the above line is effectively reading from a socket. http://hackage.haskell.org/package/network-2.8.0.0/docs/Network-Socket-ByteString.html#v:recv returns zero-length bytestrings once the peer closes the connection. Which causes an uncontrolled loop that just appends empty bytestrings to the buffer.

**Comment by lucasdicioccio** [comment]
I think you're right, in a practical setup, there's very likely outgoing traffic (i.e., writes on the socket) leading to exceptions and clients closing the raw-connection. However there are still cases where we could end in this loop when clients send no data and should not assume well-behaved clients (doing periodic http2-pings to verify everything is fine should be enough to workaround the issue).

A bit overwhelmed these days: can you write a minimal repro case?
Feels like RawConnection would only needs a netcat to simulate a server.

**Comment by lucasdicioccio** [comment]
Started a branch at https://github.com/lucasdicioccio/http2-client/tree/stop-polling-on-eof .

**Comment by lucasdicioccio** [comment]
It's fixed in that above branch, but I'd rather convince people to look into `0.9.0.0` (to be released on Hackage soonish).

**Comment by lucasdicioccio** [comment]
That said, we could cherry-pick the change and release a patch in the `0.8.x.y` branch (will likely do after 0.9 and children libs have been updated).

**Comment by lucasdicioccio** [comment]
0.9 has been on Hackage now! Thanks you Filippo for the debugging and reporting the error.
