### ISSUE TITLE
Provide a way to open a frame connection over a raw socket

### ISSUE THREAD

**Issue by refi64** [lucasdicioccio/http2-client#69]
I'm hoping to use http2-client-grpc with unix domain sockets, but http2-client doesn't provide anything like `frameHttp2RawConnection` publicly, so there's no way to do this right now...

**Comment by lucasdicioccio** [comment]
Hi! it shoul be doable. Do you mind trying to implement a constructor for `Network.HTTP2.Client.RawConnection` over unix domain sockets?

hint: it would likely look like https://hackage.haskell.org/package/http2-client-0.9.0.0/docs/src/Network.HTTP2.Client.RawConnection.html#newRawHttp2Connection with different hints

**Comment by refi64** [comment]
So if there were a constructor for RawConnection, there would also have to be a FrameConnection that uses it as well, right?

**Comment by lucasdicioccio** [comment]
Correct. There's a hidden function named `frameHttp2RawConnection :: RawHttp2Connection
  -> ClientIO Http2FrameConnection` in the `Network.HTTP2.Client.FrameConnection` module. If you have time to write a patch do not hesitate to export this function from that module.
