### ISSUE TITLE
Release to hackage?

### ISSUE THREAD

**Issue by akshaymankar** [lucasdicioccio/http2-client#73]
Hello, I am exploring solutions to [an issue](https://github.com/haskell-grpc-native/http2-grpc-haskell/issues/42) in a downstream library `http2-client-grpc` and it looks like the unreleased changes from https://github.com/lucasdicioccio/http2-client/pull/70 will be very helpful in fixing those. It would make life much easier if the latest code on the master branch of this repository was released to hackage.

**Comment by lucasdicioccio** [comment]
Hi Akshay! thanks for the small reminder. I'll look into doing that over the week-end, or next week at worst.

**Comment by lucasdicioccio** [comment]
Here we go.

https://hackage.haskell.org/package/http2-client-0.10.0.0

Please let me know if it's good for you => If so please leave the issue open as I'll push a post-release commit.

With <3, Lucas

**Comment by akshaymankar** [comment]
Thanks for the quick response!
