### ISSUE TITLE
Release 0.10.0.1 to Hackage

### ISSUE THREAD

**Issue by ProofOfKeags** [lucasdicioccio/http2-client#80]
Not sure what goes into this but it looks like it is holding up some downstream changes from being merged such as https://github.com/haskell-grpc-native/http2-grpc-haskell/pull/46

**Comment by epoberezkin** [comment]
it looks like it's time for the next already... @lucasdicioccio could we please release it? for now we would use from GitHub...

**Comment by lucasdicioccio** [comment]
Thanks for the ping @epoberezkin . Will do that over the WE.

**Comment by epoberezkin** [comment]
Thank you!

**Comment by lucasdicioccio** [comment]
@epoberezkin actually the only diff seems to be the package bounds?

I see that some bounds where only relaxed so the only new change is to make a revision relaxing `http2`.

I've done so on a new 0.10.0.0 revision on Hackage to be kind on Hackage resources, if a full upload is required, ping me.

![Screenshot from 2022-04-11 09-50-18](https://user-images.githubusercontent.com/213458/162690046-b5534c9c-1cf1-49c5-b680-6755020413b4.png)
